export const PREVIEW_PROFILE = {
  username: "sarah_reads",
  display_name: "Sarah Mitchell",
  bio: "Book lover from San Francisco | Fiction & self-improvement | 40+ books/year",
  avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
  favoriteGenres: ["Fiction", "Self-Help", "Mystery"],
  socialLinks: [
    { id: "1", platform: "instagram", value: "sarah.reads" },
    { id: "2", platform: "twitter", value: "sarahreads" },
  ],
};

export const PREVIEW_BOOKS = [
  // Currently Reading
  {
    id: "preview-1",
    title: "Atomic Habits",
    author: "James Clear",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    status: "currently_reading" as const,
    rating: null,
    notes: "The 1% improvement concept is game-changing!",
    current_page: 156,
    total_pages: 320,
  },
  {
    id: "preview-2",
    title: "The Midnight Library",
    author: "Matt Haig",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    status: "currently_reading" as const,
    rating: null,
    notes: "Beautiful concept about infinite possibilities",
    current_page: 89,
    total_pages: 304,
  },

  // Completed
  {
    id: "preview-3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Best sci-fi I've read! Rocky is amazing.",
  },
  {
    id: "preview-4",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Changed how I think about wealth.",
  },
  {
    id: "preview-5",
    title: "Educated",
    author: "Tara Westover",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Incredible memoir. Inspiring journey.",
  },
  {
    id: "preview-6",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    cover_url: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    status: "completed" as const,
    rating: 4,
    notes: "That twist ending!",
  },
  {
    id: "preview-7",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Mind-expanding history of humanity.",
  },
  {
    id: "preview-8",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
    status: "completed" as const,
    rating: 4,
    notes: "Beautiful nature writing.",
  },

  // To Read
  {
    id: "preview-9",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    cover_url: "https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg",
    status: "to_read" as const,
    rating: null,
    notes: "Everyone's recommending this!",
  },
  {
    id: "preview-10",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    cover_url: "https://covers.openlibrary.org/b/isbn/9781649374042-L.jpg",
    status: "to_read" as const,
    rating: null,
    notes: "Fantasy with dragons - yes please!",
  },
];
