export const PREVIEW_PROFILE = {
  username: "sophia_reads",
  display_name: "Sophia Martinez",
  bio: "Book lover | Fiction enthusiast | Always reading ✨",
  avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
  favoriteGenres: ["Fiction", "Mystery", "Self-Help", "Science Fiction"],
  socialLinks: [
    { id: "1", platform: "instagram", value: "sophia.reads" },
    { id: "2", platform: "goodreads", value: "sophiamartinez" },
    { id: "3", platform: "twitter", value: "sophia_reads" },
  ],
};

export const PREVIEW_BOOKS = [
  // Currently Reading (3 books)
  {
    id: "preview-1",
    title: "The Midnight Library",
    author: "Matt Haig",
    cover_url: "https://covers.openlibrary.org/b/id/12559530-L.jpg",
    status: "currently_reading" as const,
    rating: null,
    notes: "Loving the concept of infinite possibilities! The writing style is so engaging.",
    current_page: 187,
    total_pages: 304,
    date_started: "2025-01-15",
  },
  {
    id: "preview-2",
    title: "Atomic Habits",
    author: "James Clear",
    cover_url: "https://covers.openlibrary.org/b/id/12648216-L.jpg",
    status: "currently_reading" as const,
    rating: null,
    notes: "Taking notes on every chapter. The 1% improvement concept is brilliant!",
    current_page: 95,
    total_pages: 320,
    date_started: "2025-01-20",
  },
  {
    id: "preview-3",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    cover_url: "https://covers.openlibrary.org/b/id/12897553-L.jpg",
    status: "currently_reading" as const,
    rating: null,
    notes: "The character development is incredible. Can't put this down!",
    current_page: 210,
    total_pages: 389,
    date_started: "2025-01-10",
  },

  // Completed (8 books)
  {
    id: "preview-4",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover_url: "https://covers.openlibrary.org/b/id/11949683-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Best sci-fi I've read in years! The humor and science blend perfectly. Rocky is my favorite character ever.",
    date_completed: "2025-01-05",
  },
  {
    id: "preview-5",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    cover_url: "https://covers.openlibrary.org/b/id/10394822-L.jpg",
    status: "completed" as const,
    rating: 4,
    notes: "Mind-blowing twist ending! Didn't see it coming at all.",
    date_completed: "2024-12-28",
  },
  {
    id: "preview-6",
    title: "Educated",
    author: "Tara Westover",
    cover_url: "https://covers.openlibrary.org/b/id/8679541-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "An incredibly powerful memoir. Her journey is inspiring and heartbreaking.",
    date_completed: "2024-12-20",
  },
  {
    id: "preview-7",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    cover_url: "https://covers.openlibrary.org/b/id/10522975-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Changed my perspective on wealth and happiness. Everyone should read this.",
    date_completed: "2024-12-15",
  },
  {
    id: "preview-8",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    cover_url: "https://covers.openlibrary.org/b/id/12841398-L.jpg",
    status: "completed" as const,
    rating: 4,
    notes: "Beautiful nature descriptions. The mystery kept me hooked!",
    date_completed: "2024-12-10",
  },
  {
    id: "preview-9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    cover_url: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    status: "completed" as const,
    rating: 4,
    notes: "A timeless story about following your dreams. Simple yet profound.",
    date_completed: "2024-12-01",
  },
  {
    id: "preview-10",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    cover_url: "https://covers.openlibrary.org/b/id/8645183-L.jpg",
    status: "completed" as const,
    rating: 5,
    notes: "Mind-expanding history of humanity. Makes you think about everything differently.",
    date_completed: "2024-11-22",
  },

  // To Read (2 books)
  {
    id: "preview-11",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    cover_url: "https://covers.openlibrary.org/b/id/12897554-L.jpg",
    status: "to_read" as const,
    rating: null,
    notes: "Heard amazing things about this! Can't wait to dive in.",
  },
  {
    id: "preview-12",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    cover_url: "https://covers.openlibrary.org/b/id/11044159-L.jpg",
    status: "to_read" as const,
    rating: null,
    notes: "The premise sounds fascinating - living for centuries but being forgotten.",
  },
];
